######################## default configuration ####################
baseURL = "https://blog.kouki.io"
languageCode = "en-us"
title = "Kouki's blog"
theme = "liva-tmp"
summaryLength = "100"
paginate = 6
disqusShortname = ""
pygmentsUseClasses = true
pygmentsCodefences = true
defaultContentLanguage = "ja"
hasCJKLanguage = true

[permalinks]
  post = "/:year/:month/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[marketing]
  google_analytics = ""
  google_tag_manager = "GTM-57L8VGF"

[taxonomies]
    tag = "tags"
    category = "categories"

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  [[params.plugins.css]]
  URL = "plugins/fontawesome/css/all.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "https://kouki.io"
  weight = 1

  # footer menu
  [[menu.footer]]
  name = "Home"
  URL = ""
  pre = "<i class='ti-home'></i>"
  weight = 1

  [[menu.footer]]
  name = "About"
  URL = "https://kouki.io"
  pre = "<i class='ti-user'></i>"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "https://twitter.com/kouki_tsuji"
  pre = "<i class='ti-email'></i>"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
portfolio = "https://kouki.io/"
# Meta data
description = "This is meta description"
author = "辻幸喜 / Kouki Tsuji"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
#mobile = "0124857985320"
#email = "demo@email.com"
#location = "Dhaka, Bangladedsh"
# copyright
copyright = "&copy; 2020 [Kouki Tsuji](https://kouki.io)"
twitterID = "kouki_tsuji"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

############################# social site ########################
[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/kouki_tsuji"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/koukitsuji"

[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/kouki.tsuji.626"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/kouki_tsuji/"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "qiita"
#icon = "ti-ink-pen" # themify icon : https://themify.me/themify-icons
#link = "https://qiita.com/kouki_tsuji"
